### ISSUE TITLE
Unnecessary ID column

### ISSUE THREAD

**Issue by tvanantwerp** [TaxFoundation/worldwide-corporate-tax-rates#3]
https://github.com/TaxFoundation/worldwide-corporate-tax-rates/blob/master/final-outputs/rate_time_series.csv

https://github.com/TaxFoundation/worldwide-corporate-tax-rates/blob/master/final-data/final_data_long.csv

**Comment by elkeasen** [comment]
Should be fixed.

**Comment by tvanantwerp** [comment]
Fixes haven't been pushed to GitHub yet--I still see the last edit as 6 months ago.
